volumes:
    db:

services:
    finance_db:
        build: ./database
        environment:
            - POSTGRES_DB=finance
            - POSTGRES_USER=ChangeMe
            - POSTGRES_PASSWORD=ChangeMe
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "5433:5432"